In [2]:
import torch
import numpy as np
from random import shuffle
import pickle

In [7]:
# prepare shuffled balanced data
with open("/home/yiqin/2018summer_project/balanced_data_small.pkl", "rb") as f:
    dic = pickle.load(f)
    train_X = dic["X"]
    train_Y = dic["Y"]
new_data = []
for i in range(len(train_X)):
    new_data.append((train_X[i], train_Y[i]))
shuffle(new_data)
train_X = []
train_Y = []
for i in range(len(new_data)):
    train_X.append(new_data[i][0])
    train_Y.append(new_data[i][1])
print(train_X[0])
print(train_Y[0])

tensor([[  93.2780,   94.1870,   61.0000],
        [  94.1870,   95.0960,   68.0000],
        [  95.0960,   96.0050,   65.0000],
        [  96.0050,   96.9150,   66.0000],
        [  96.9170,   97.2200,   63.0000],
        [  97.2200,   97.5230,   63.0000],
        [  97.5230,   97.8260,   63.0000],
        [  97.8260,   98.4320,   58.0000],
        [  98.4320,   98.7350,   56.0000],
        [  98.7350,   99.3410,   54.0000],
        [ 115.0430,  115.3460,   61.0000],
        [ 115.3460,  115.6490,   61.0000],
        [ 115.6490,  115.9520,   61.0000],
        [ 115.9520,  116.5590,   56.0000],
        [ 116.5590,  116.8620,   58.0000],
        [ 116.8620,  117.4680,   56.0000],
        [ 117.4680,  117.7710,   54.0000],
        [ 117.7710,  118.6800,   49.0000]], dtype=torch.float64)
tensor([ 0,  0,  1,  1,  0,  0,  0,  1,  1,  1,  0,  0,  0,  0,
         1,  1,  1,  1])


In [9]:
dic = {}
dic["X"] = train_X
dic["Y"] = train_Y
input_dim2 = []
for i in range(len(train_X)):
    input_dim2.append(torch.cat([train_X[i][:,1].unsqueeze(1) - train_X[i][:,0].unsqueeze(1),
                                 train_X[i][:,2].unsqueeze(1)], dim = 1))
dic["X2"] = input_dim2
f = open("balanced_data_shuffle.pkl", "wb")
pickle.dump(dic, f)
f.close()

print(len(dic["X2"]))
print(len(dic["X"]))
print(len(dic["Y"]))

19666
19666
19666


In [20]:
#

# load data from file
with open("/home/yiqin/2018summer_project/DeepMusic/pitch_data.pkl", "rb") as f:
    dic = pickle.load(f)
    train_X = dic["X"]
    train_Y = dic["Y"]
    #time_X = dic["time"]
    
"""for i in range(train_Y.shape[0]):
    train_Y[i] = torch.from_numpy((train_Y[i] == 4).astype(int)).float()
    """
    
with open("/home/yiqin/2018summer_project/balanced_target.pkl", "rb") as f:
    balanced_train_Y = np.array(pickle.load(f))
print(balanced_train_Y[50].reshape(-1))
print(train_Y[50].reshape(-1))

[0 0 0 0 0 1 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1 1 1 0 0
 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0
 0 0 1 1 1 1 1 1 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1 1 1
 1 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 1 1 1 1 1 0 0 0
 0 0 1 1 1 1 1 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1 1 1
 1 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 1 1 1 1 0 0 0
 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1 1
 1 1 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 1 1 1 1 1 0 0 0
 0 0 1 1 1 1 1 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 1 1 1
 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 1 1 1 1 1]
[2 3 3 3 3 3 3 3 3 4 2 3 3 3 3 3 3 4 2 3 3 3 4 2 3 3 3 3 3 3 3 3 3 3 4 2 3
 3 3 3 3 3 3 3 3 3 3 4 2 3 3 3 3 3 3 3 3 4 2 3 3 3 3 3 3 3 3 3 3 4 2 3 3 3
 3 3 3 3 3 3 3 4 2 3 3 3 3 3 3 3 4 2 3 3 3 3 3 3 3 3 3 4 2 3 3 3 3 3 3 3 3
 4 2 3 3 3 3 3 3 3 3 3 4 0 2 3 3 3 3 3 3 3 3 4 2 3 3

In [13]:
def target_factorize(target, balanced_target, input_data):
    train_X = input_data
    train_Y = target
    new_label = []
    new_input = []
    for i, target in enumerate(train_Y):
        two_list = []
        four_list = []
        # in case of bad data
        target[-1] = 4
        loc = 0
        two_list.append(0)
        for label in target:
            if int(label[0]) == 4:
                two_list.append(loc + 1)
                four_list.append(loc)
            loc = loc + 1
        two_list.pop()
        prev = 0
        for j in range(2, len(four_list), 3):
            new_label.append(torch.from_numpy(balanced_target[i][prev:four_list[j]+1].squeeze()))
            new_input.append(torch.from_numpy(train_X[i][prev:four_list[j]+1]))
            prev = four_list[j]+1
            end = j
        if j != len(four_list) - 1:
            new_label.append(torch.from_numpy(balanced_target[i][prev:].squeeze()))
            new_input.append(torch.from_numpy(train_X[i][prev:]))
    return new_label, new_input

#new_label, new_input = target_factorize(target=train_Y, balanced_target=balanced_train_Y, input_data=train_X)

In [68]:
import pickle

dic = {}
dic["X"] = new_input
dic["Y"] = new_label
f = open("balanced_data_small.pkl", "wb")
pickle.dump(dic, f)
f.close()

In [70]:
input_dim2 = []
for i in range(len(new_input)):
    input_dim2.append(torch.cat([new_input[i][:,1].unsqueeze(1) - new_input[i][:,0].unsqueeze(1),
                                 new_input[i][:,2].unsqueeze(1)], dim = 1))
dic["X2"] = input_dim2
f = open("balanced_data_small.pkl", "wb")
pickle.dump(dic, f)
f.close()

In [ ]:
"""def input_transform(train_x, time_x, i):
    output = torch.from_numpy(np.array([train_x[i], time_x[i]]))
    return output.transpose(1, 0).to(device)
"""

def input_transform(train_x, i):
    output = torch.Tensor([train_x[i][:,1] - train_x[i][:,0], train_x[i][:,2]])
    return output.squeeze(0).transpose(1,0).to(device)
    
    
def input_factorize(train_x):
    output = []
    for i in range(len(train_x)):
        for item in np.array_split(train_x[i], train_x[i].shape[0] / 30):
            output.append(item)
    return output


def target_factorize(train_y):
    output = []
    for i in range(len(train_y)):
        for item in np.array_split(train_y[i], train_y[i].shape[0] / 30):
            output.append(torch.Tensor(item).squeeze())
    return output

def target_transform(train_y):
    output = torch.zeros((1, 2))
    output[0, int(train_y)] = 1
    return output.unsqueeze(1).to(device)


In [21]:
# padding the data tensor:
import torch.nn.functional as F

with open("/home/yiqin/2018summer_project/balanced_data_small.pkl", "rb") as f:
    dic = pickle.load(f)
    train_X = dic["X2"]
    train_Y = dic["Y"]

padding_data = []
padding_label = []
maximum = 0
for i in range(len(train_X)):
    if train_X[i].shape[0] < 3:
        continue
    padding_data.append(F.pad(train_X[i], (0,0,0,70-train_X[i].shape[0]), value = 0))
    padding_label.append(F.pad(train_Y[i], (0, 70-train_X[i].shape[0]), value = 2))
    
dic = {}
dic["X"] =  padding_data
dic["Y"] = padding_label

f = open("balanced_data_padding.pkl", "wb")
pickle.dump(dic, f)
f.close()

In [23]:
data = torch.stack(padding_data)
print(data.shape)

torch.Size([19626, 70, 2])


In [24]:
dataset = torch.util.data.Dataset(padding_data)

AttributeError: module 'torch' has no attribute 'util'

In [21]:
with open("/home/yiqin/2018summer_project/balanced_data_small.pkl", "rb") as f:
    dic = pickle.load(f)
    smooth_train_X = dic["X2"]
    
with open("/home/yiqin/2018summer_project/smooth_data.pkl", "rb") as f:
    smooth_train_Y = pickle.load(f)
smooth_train_Y, _ = target_factorize(train_Y, smooth_train_Y, train_X)

tensor([ 0.5000,  0.2500,  0.1250,  0.0625,  0.0312,  0.0312,  0.0312,
         0.0625,  0.1250,  0.2500,  0.5000,  1.0000,  0.5000,  0.2500,
         0.1250,  0.0625,  0.0312,  0.0312,  0.0312,  0.0625,  0.1250,
         0.2500,  0.5000,  1.0000,  0.5000,  0.2500,  0.1250,  0.0625,
         0.0312,  0.0312,  0.0625,  0.1250,  0.2500,  0.5000,  1.0000], dtype=torch.float64)


In [22]:
print(smooth_train_Y[1000].shape)
print(smooth_train_X[1000].shape)

torch.Size([14])
torch.Size([14, 2])


In [23]:
f = open("/home/yiqin/2018summer_project/smooth_data.pkl", "wb")
dic = {}
dic["X"] = smooth_train_X
dic["Y"] = smooth_train_Y
pickle.dump(dic, f)
f.close()